=== kaige1234/dubbo-dafenqi/xl-es/src/main/java/com/xl/es/script/builder/xml/script-mapper.dtd
<?xml version="1.0" encoding="UTF-8" ?>

<!ELEMENT mapper (script* | insert* | update* | delete* | select* )+>
<!ATTLIST mapper
xmlns:fo CDATA #IMPLIED
namespace CDATA #IMPLIED
>

<!ELEMENT select (#PCDATA | include | trim | where | set | foreach | choose | if)*>
<!ATTLIST select
id CDATA #REQUIRED
index CDATA #IMPLIED
type CDATA #IMPLIED
parameterType CDATA #IMPLIED
resultType CDATA #IMPLIED
>

<!ELEMENT insert (#PCDATA |  include | trim | where | set | foreach | choose | if)*>
<!ATTLIST insert
id CDATA #REQUIRED
index CDATA #IMPLIED
type CDATA #IMPLIED
parameterType CDATA #IMPLIED
>

<!ELEMENT update (#PCDATA | include | trim | where | set | foreach | choose | if)*>
<!ATTLIST update
id CDATA #REQUIRED
index CDATA #IMPLIED
type CDATA #IMPLIED
parameterType CDATA #IMPLIED
>

<!ELEMENT delete (#PCDATA | include | trim | where | set | foreach | choose | if)*>
<!ATTLIST delete
id CDATA #REQUIRED
index CDATA #IMPLIED
type CDATA #IMPLIED
parameterType CDATA #IMPLIED
>

<!-- Dynamic -->

<!ELEMENT include EMPTY>
<!ATTLIST include
refid CDATA #REQUIRED
>

<!ELEMENT script (#PCDATA | include | trim | where | set | foreach | choose | if)*>
<!ATTLIST script
id CDATA #REQUIRED
>

<!ELEMENT trim (#PCDATA | include | trim | where | set | foreach | choose | if)*>
<!ATTLIST trim
prefix CDATA #IMPLIED
prefixOverrides CDATA #IMPLIED
suffix CDATA #IMPLIED
suffixOverrides CDATA #IMPLIED
>
<!ELEMENT where (#PCDATA | include | trim | where | set | foreach | choose | if)*>
<!ELEMENT set (#PCDATA | include | trim | where | set | foreach | choose | if)*>

<!ELEMENT foreach (#PCDATA | include | trim | where | set | foreach | choose | if)*>
<!ATTLIST foreach
collection CDATA #REQUIRED
item CDATA #IMPLIED
index CDATA #IMPLIED
open CDATA #IMPLIED
close CDATA #IMPLIED
separator CDATA #IMPLIED
>

<!ELEMENT choose (when* , otherwise?)>
<!ELEMENT when (#PCDATA | include | trim | where | set | foreach | choose | if)*>
<!ATTLIST when
test CDATA #REQUIRED
>
<!ELEMENT otherwise (#PCDATA | include | trim | where | set | foreach | choose | if)*>

<!ELEMENT if (#PCDATA | include | trim | where | set | foreach | choose | if)*>
<!ATTLIST if
test CDATA #REQUIRED
>

=== kaige1234/dubbo-dafenqi/xl-es/src/main/resources/script/merchant.script.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mapper PUBLIC "-//script.org//DTD Mapper 3.0//EN"  "http://script.org/dtd/script-mapper.dtd">
<mapper namespace="merchant">
	<!-- 默认查询 -->
	<select id="merchantQuery" index="xl" type="merchant" resultType="com.xl.es.data.doc.Merchant">
		{
	      "from": ${startIndex},
    	  "size": ${pageSize},
    	  "query": {
		    "bool": {
		      "must": [
		      	{"exists":{"field":"lId"}}
		      	<if test="strProvinceCode!=null and strProvinceCode!=''">
		        ,{
		          "match": {
		            "strProvinceCode": #{strProvinceCode}
		          }
		        }
		        </if>
		       <if test="strCityCode!=null and strCityCode!=''">
		        ,{
		          "match": {
		            "strCityCode": #{strCityCode}
		          }
		        }
		        </if>
		        <if test="strAreaCode!=null and strAreaCode!=''">
		        ,{
		          "match": {
		            "strAreaCode": #{strAreaCode}
		          }
		        }
		        </if>
		        <if test="strStreetCode!=null and strStreetCode!=''">
		        ,{
		          "match": {
		            "strStreetCode": #{strStreetCode}
		          }
		        }
		        </if>
		        <if test="nBusiness!=null and nBusiness!=''">
		        ,{
		          "match": {
		            "nBusinessId": #{nBusiness}
		          }
		        }
		        </if>
		        <if test="nBusiness2!=null and nBusiness2!=''">
		        ,{
		          "match": {
		            "nBusiness2Id": #{nBusiness2}
		          }
		        }
		        </if>
		        <if test="keyword!=null and keyword!=''">
		        ,{
		          "multi_match": {
		            "query": #{keyword},
		            "fields": [
		              "strName",
		              "strBusinessRange",
		              "goods.strGoodsName"
		            ]
		          }
		        }
		        </if>
		      ]
		    }
		  }
		 <if test="sort!=null and sort=='range'.toString()">
		  ,"sort": [
		    {
		      "_geo_distance": {
		        "strLongitudeAndLatitude": {
		          "lat":  #{lat},
		          "lon": #{lon}
		        },
		        "order":         "asc",
		        "unit":          "km", 
		        "distance_type": "plane" 
		      }
		    }
		  ]
		  </if>
		  
		  <if test="sort!=null and sort=='start'.toString()">
		  ,"sort": {
		    "lHistoryAmount": {
		      "order": "desc"
		    }
		  }
		  </if>
		  
		  <if test="sort!=null and sort=='near'.toString()">
		  ,"sort": {
		    "dtFirstAuditTime": {
		      "order": "desc"
		    }
		  }
		  </if>
		}
	</select>
</mapper>
